# This is a basic workflow to help you get started with Actions

name: Free Courses Enroller For Udemy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  schedule:
    - cron: '*/15 * * * *'  # testing trigger time

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Runs a set of commands using the runners shell
      - name: Installing Requirements
        run: | 
          python -m pip install --upgrade pip
          pip install bs4 requests pynput pyautogui pillow
          choco install burp-suite-free-edition
      
      - name: Loading Environment Variables
        env: |
            ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
            SESSION_ID: ${{secrets.SESSION_ID}}
            FREE_IMAGEKEY: ${{secrets.FREE_IMAGEKEY}}
            IGNORE_ACCESSTOKEN: ${{secrets.IGNORE_ACCESSTOKEN}}
            FROM_DAY: ${{secrets.FROM_DAY}}
            TO_DAY: ${{secrets.TO_DAY}}
            REQUESTS_LIMIT: ${{secrets.REQUESTS_LIMIT}}
            ENROLLS_LIMIT: ${{secrets.ENROLLS_LIMIT}}
            DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
            DB_TABLE_NAME: ${{secrets.DB_TABLE_NAME}}
            DB_TABLE_NOTIFY: ${{secrets.DB_TABLE_NOTIFY}}

      - name: Setting up Burpsuite
        run: |
          python redo.py burp.txt 1 0 
          python takescreenshoot.py
      
      - name: Setting up Proxy Settings
        run: | 
          python redo.py proxy.txt 1 0
          python takescreenshoot.py
        
      - name: Setting up Chrome for Cloudflare bypass
        run: |
          python redo.py chrome.txt 1 0
          python takescreenshoot.py
        
      - name: Perform Click for Verification
        run: |
          python redo.py clicktoverify.txt 20 5
          python takescreenshoot.py
        
      - name: Running Python Script  
        run: python main.py
          
          
          
          
          
          
          
      
      
